name: Build RAX3000M‑NAND‑MTK mtd‑rw‑patch 6.6
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache ecj fastjar file g++ gawk gettext git libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python3 python3-setuptools python3-yaml unzip wget zlib1g-dev flex bison libtool rsync

      - name: Feeds update install
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate config NAND‑MTK
        run: |
          echo "CONFIG_TARGET_mediatek=y" > .config
          echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic_DEVICE_cmcc_rax3000m_nand_mtk=y" >> .config
          make defconfig

      - name: Download dl sources
        run: make download -j$(nproc)

      - name: Compile firmware verbose log
        run: make -j1 V=sc

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: RAX3000M-NAND-MTK-6.6-unlock
          path: bin/targets/mediatek/filogic/*.bin
